version: '3'

services:
  app:
    image: 'yasn:latest'
    build:
      context: .
    ports:
      - "8080:8080"
    container_name: app
    depends_on:
      - yasn
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/yasn_db
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    volumes:
      - ./src/main/resources:/var
  yasn:
    image: 'postgres:13.1-alpine'
    container_name: db
    environment:
      - POSTGRES_DB=yasn_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - .:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"